version: "3.9"
networks:
  data-api:
    driver: bridge
    name: data-api
  dojo-stack:
    driver: bridge
    name: dojo-stack
services:
  api:
    build: ./
    ports:
      - "8001:8000"
    env_file:
      - api.env
    environment:
      - SQL_URL
      - SQL_PORT
      - SQL_USER
      - SQL_PASSWORD
    networks:
      - dojo-stack
      - data-api

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=askem
    networks:
      - data-api
    profiles: [ "dev" ]
volumes:
  dataset-storage: {}
