version: "3.9"
networks:
  data-api:
    driver: bridge
    name: data-api
  data-annotation-stack:
    driver: bridge
    name: data-annotation-stack
services:
  api:
    container_name: data-service-api
    build:
      context: ./
      dockerfile: docker/Dockerfile
    ports:
      - "8001:8000"
    env_file:
      - api.env
    environment:
      - NEO4J_ENABLED
    networks:
      - data-annotation-stack
      - data-api
  elasticsearch:
    profiles: ["local", "tds-testing"]
    image: elasticsearch:${STACK_VERSION}
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
      - action.auto_create_index=false
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200
    networks:
      - data-api
    healthcheck:
      test: curl http://localhost:9200/_cluster/health?wait_for_status=yellow || exit 1
      interval: 10s
      timeout: 10s
      retries: 10
  migrations:
    profiles: ["tds-api-only", "tds-api", "local"]
    container_name: data-service-migrations
    build:
      context: ./
      dockerfile: docker/Dockerfile.migrations
    entrypoint: /run_migrations.sh
    env_file:
      - api.env
    networks:
      - data-api
volumes:
  tds_data:
    driver: local
  neo4j_data:
    driver: local
  elasticsearch_data:
    driver: local
  kibanadata:
    driver: local