version: "3.9"
networks:
  data-api:
    driver: bridge
    name: data-api
  data-annotation-stack:
    driver: bridge
    name: data-annotation-stack
services:
  rdb:
    image: "postgres:15.0"
    ports:
      - "8032:5432"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=askem
    networks:
      - data-api
  api:
    build: ./
    ports:
      - "8001:8000"
    env_file:
      - api.env
    networks:
      - data-annotation-stack
      - data-api
    depends_on:
      - rdb
    volumes:
      - $PWD/tds:/api/tds
