version: "3.9"
networks:
  data-api:
    driver: bridge
    name: data-api
services:
  api:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - api.env
    environment:
      - SQL_URL
      - SQL_PORT
      - SQL_USER
      - SQL_PASSWORD

  db:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=askem
    profiles: [ "dev" ]
volumes:
  dataset-storage: {}
