version: "3.9"
services:
  rdb:
    image: "postgres:15.0"
    ports:
      - "8032:5432"
    environment:
      - POSTGRES_PASSWORD=dev
      - POSTGRES_USER=dev
      - POSTGRES_DB=askem
  api:
    build: ./
    ports:
      - "8000:8000"
    env_file:
      - api.env
    depends_on:
      - rdb
    volumes:
      - $PWD/tds:/api/tds
