[tool.poetry]
name = "tds"
version = "0.1.1"
description = "The API that sits on top of the data store for the ASKEM program."
authors = ["Five Grant <five@jataware.com>"]
readme = "README.md"
packages = [{include = "src"}]
license = "MIT"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/DARPA-ASKEM/data-store-api/issues"

[tool.poetry.dependencies]
python = "^3.10"
dbml-builder = "^0.2.2"
sqlalchemy = "^1.4.42"
pydantic = "^1.10.2"
pylint = "^2.15.5"
uvicorn = "^0.19.0"
fastapi = "^0.85.1"
click = "^8.1.3"
pytest = "^7.1.3"
requests = "^2.28.1"
psycopg2-binary = "^2.9.4"


[tool.poetry.scripts]
tds = "src.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[virtualenvs]
in-project = true

[tool.pytest.ini_options]
filterwarnings = ["ignore::DeprecationWarning"]


[tool.pylint.master]
# Since the data store is part of an R&D project, it makes sense to move fast
# and leave TODOs for later.
disable=["fixme"]
# Pylint should not run on the the generated files
ignore=["generated"]
extension-pkg-whitelist=["pydantic"]
jobs=4

[tool.pylint.basic]
good-names=["id"]

[tool.pylint.variables]
allowed-redefined-builtins=["id"]

[tool.pylint.format]
max-line-length=93
