version: "3.9"
services:
  api:
    container_name: data-service-api-testing
    build:
      context: ./
      dockerfile: docker/Dockerfile.test
    ports:
      - "8001:8000"
    env_file:
      - api.env
    environment:
      - NEO4J_ENABLED
      - SQL_URL=""
    depends_on:
      elasticsearch:
        condition: service_healthy
    volumes:
      - $PWD/tests:/api/tests
      - $PWD/tds:/api/tds
      - $PWD/migrate:/api/migrate