version: "3.9"
services:
  api:
    environment:
      - NEO4J_ENABLED
      - SQL_CONN_STR=sqlite:///test.db
      - SEED_DATA=false
      - SQL_NOW_STATEMENT='CURRENT_TIMESTAMP'
    depends_on:
      elasticsearch:
        condition: service_healthy