---
# Automatically build Docker images on changes to dev and push them to a
# Container Registry using HCL Bake file.

name: Build Docker Images

on:
  push:
    branches: ['main']
    tags: ['*']

jobs:
  # Run correctness checks
  correctness:
    uses: ./.github/workflows/correctness.yaml

  # Run formatting checks
  formatting:
    uses: ./.github/workflows/formatting.yaml

  # Call the Tag Generator to generate an image tag to use
  tag-generator:
    uses: darpa-askem/.github/.github/workflows/tag-generator.yaml@main
    with:
      branch: 'main'

  # Build and Publish all targets associated with specified group
  bake:
    needs:
  # Temorarily remove these to allow build while we fix testing
  #      - correctness
  #      - formatting
      - tag-generator
    uses: darpa-askem/.github/.github/workflows/bake-publish.yml@main
    with:
      file: 'docker-bake.hcl'
      group: 'prod'
      registry: 'ghcr.io'
      organization: ${{ github.repository_owner }}
      tag: ${{ needs.tag-generator.outputs.tag }}
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}

  # Execute simulation-integration reporting
  simulation-integration:
    runs-on: ubuntu-latest
    needs: 
      - bake
    steps:
      - name: Report
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHP_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/DARPA-ASKEM/simulation-integration/actions/workflows/report.yaml/dispatches \
            -d '{"ref":"main","inputs":{}}'

  # Execute simulation-integration reporting
  knowledge-middleware:
    runs-on: ubuntu-latest
    needs: 
      - bake
    steps:
      - name: Report
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GHP_ACCESS_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/DARPA-ASKEM/knowledge-middleware/actions/workflows/report.yaml/dispatches \
            -d '{"ref":"main","inputs":{}}'