---
# Automatically build Docker images on changes to dev and push them to a
# Container Registry using HCL Bake file.

name: Build Docker Images

on:
  push:
    branches: ['main']
    tags: ['*']

jobs:
  # Run correctness checks
  correctness:
    uses: ./.github/workflows/correctness.yaml

  # Run formatting checks
  formatting:
    uses: ./.github/workflows/formatting.yaml

  # Call the Tag Generator to generate an image tag to use
  tag-generator:
    uses: darpa-askem/.github/.github/workflows/tag-generator.yaml@main
    with:
      branch: 'dev'

  # Build and Publish all targets associated with specified group
  bake:
    needs:
      - correctness
      - formatting
      - tag-generator
    uses: darpa-askem/.github/.github/workflows/bake-publish.yml@main
    with:
      file: 'docker-bake.hcl'
      group: 'prod'
      registry: 'ghcr.io'
      organization: ${{ github.repository_owner }}
      tag: ${{ needs.tag-generator.outputs.tag }}
    secrets:
      username: ${{ github.repository_owner }}
      password: ${{ secrets.GITHUB_TOKEN }}
