---
name: Correctness
on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Start containers
        run: docker-compose --env-file api.env.sample -f "docker-compose.yml" -f "docker/overrides/docker-compose.testing.override.yml" --profile tds-testing up -d --build
      - name: Stop containers
        if: always()
        run: docker-compose --env-file api.env.sample -f "docker-compose.yml" -f "docker/overrides/docker-compose.testing.override.yml" --profile tds-testing down