---
name: Test
on:
  workflow_call:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up test.
        run: |
          cp api.env.sample api.env
          cp docker/overrides/docker-compose.testing.override.yml docker-compose.override.yml
      - name: Run Test Suite
        run: |
          docker-compose --env-file api.env --profile tds-testing up --abort-on-container-exit --build

      - name: Clean Up
        if: always()
        run: docker-compose --env-file api.env --profile tds-testing down